apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "akka-404-server.fullname" . }}
  labels:
    app: {{ template "akka-404-server.name" . }}
    chart: {{ template "akka-404-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "akka-404-server.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "akka-404-server.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          # livenessProbe:
            # httpGet:
              # path: /healthz
              # port: http
            # initialDelaySeconds: 5
            # periodSeconds: 20  
          # readinessProbe:
            # httpGet:
              # path: /healthz
              # port: http
            # initialDelaySeconds: 5
            # periodSeconds: 20
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
